version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    reviewers:
      - gr8monk3ys
    ignore:
      - dependency-name: "cachix/install-nix-action"
        versions:
          - "31.10.0"
