[palettes.danse]
comment = '{{comment}}'
yellow = '{{yellow}}'
vermilion = '{{vermilion}}'
blue = '{{blue}}'
green = '{{green}}'
terracotta = '{{terracotta}}'
cyan = '{{cyan}}'
magenta = '{{magenta}}'
